import type {
  ForgeRank,
  Language,
  ProjectState,
  SortOption,
  StatusFilter,
} from "@/components/studio/types";

export const dashboardCopy = {
  ja: {
    topEyebrow: "FORGE STUDIO",
    topTitle: "Forge Studio",
    topSubtitle: "作品を絞り込んで、次の作業へ進むための一覧。",
    quickReload: "再読み込み",
    rankReady: "準備中",
    rankWarming: "立ち上げ中",
    rankSmooth: "順調",
    rankStable: "安定運用",
    searchLabel: "検索",
    searchPlaceholder: "タイトル / タグ / app path で絞り込み",
    categoryLabel: "カテゴリ",
    statusLabel: "状態",
    sortLabel: "並び順",
    filterAll: "全カテゴリ",
    filterStatusAll: "すべて",
    filterStatusActiveDev: "Dev稼働中",
    filterStatusReady: "視聴可能",
    filterStatusNeedsRender: "初回レンダー待ち",
    filterStatusTemplate: "テンプレート / 例",
    sortRecent: "最新順",
    sortTitle: "タイトル順",
    sortCategory: "カテゴリ順",
    showingPrefix: "表示",
    showingSuffix: "件",
    syncing: "dev status syncing...",
    guideTitle: "使い方",
    guideStepWatch: "作品を見る で最新レンダーを確認",
    guideStepManage: "管理パネル で Render / Dev / Meta を操作",
    guideStepStart: "出力がない作品は Renderを作成 から始める",
    guideDismiss: "閉じる",
    sectionFiltered: "Filtered projects",
    sectionFilteredBody: "絞り込み結果です。",
    sectionActiveDev: "Running now",
    sectionActiveDevBody: "いま開発中の作品です。",
    sectionReady: "Ready to watch",
    sectionReadyBody: "最新レンダーがあります。",
    sectionNeedsRender: "Needs first render",
    sectionNeedsRenderBody: "まだ出力がありません。",
    sectionTemplate: "Templates & tools",
    sectionTemplateBody: "テンプレートと検証用です。",
    noMatchTitle: "一致する作品がありません",
    noMatchBody:
      "検索条件をゆるめるか、`pnpm create:project` で新しい作品を追加してください。",
    primaryWatch: "作品を見る",
    primaryOpenDev: "Devを開く",
    primaryRender: "Renderを作成",
    primaryRunDev: "Dev起動",
    actionManage: "管理パネル",
    actionRenderNow: "Render実行",
    actionRefreshList: "一覧更新",
    actionDeleteRender: "動画削除",
    actionDeleteProject: "プロジェクト削除",
    actionRunDev: "Dev起動",
    actionStopDev: "Dev停止",
    actionOpenDev: "Devを開く",
    actionOpenInNewTab: "新しいタブで開く",
    actionClose: "閉じる",
    actionSave: "保存",
    stateActiveDev: "Active Dev",
    stateReady: "Ready",
    stateNeedsRender: "Needs Render",
    stateTemplate: "Template",
    labelLastRendered: "Last rendered",
    labelRenderFiles: "Render files",
    labelAppPath: "App path",
    labelLatest: "Latest",
    labelNoTags: "タグ未設定",
    labelNeverRendered: "未実行 / Never rendered",
    labelUnknown: "unknown",
    manageTitle: "Project control",
    manageSubtitle: "重い操作はここでまとめて扱います。",
    panelRenders: "Renders",
    panelDev: "Dev",
    panelMeta: "Meta",
    panelLatestRender: "最新レンダー",
    panelNoRender: "レンダー動画はまだありません。",
    panelRenderBody:
      "必要なときだけ動画一覧を開き、再生・削除・再取得を行います。",
    panelDevBody: "Dev サーバーの起動・停止とログの確認をここに寄せます。",
    panelMetaBody: "作品メタと削除操作を一箇所に集約します。",
    panelPreviewStatic: "Static preview",
    panelRunningOn: "Running on",
    panelStopped: "停止中 / Stopped",
    panelLog: "Log",
    panelPid: "PID",
    panelTitle: "タイトル",
    panelDescription: "説明",
    panelTags: "タグ",
    panelCategory: "カテゴリ",
    panelThumbnail: "サムネイル",
    placeholderTitle: "title",
    placeholderDescription: "description",
    placeholderTags: "tags (comma separated)",
    placeholderCategory: "category",
    placeholderThumbnail: "thumbnail path (e.g. public/thumbnail.svg)",
    previewTitle: "Quick Preview",
    previewApp: "App",
    previewUpdated: "Updated",
    previewSize: "Size",
    msgDevStartFailed: "Dev起動に失敗しました。",
    msgDevConnect: "Dev接続",
    msgDevStarted: "Dev起動",
    msgDevStartRequestFailed: "Dev起動リクエストに失敗しました",
    msgDevStopFailed: "Dev停止に失敗しました。",
    msgAlreadyStopped: "既に停止中",
    msgDevStopped: "Dev停止",
    msgDevStopRequestFailed: "Dev停止リクエストに失敗しました",
    msgDevNotFound: "Devサーバーが見つかりません",
    msgRenderListFailed: "Render一覧の取得に失敗",
    msgRenderListUpdated: "Render一覧更新",
    msgNoWatchable: "まだ視聴できる動画がありません",
    msgCreateRender: "先に Render を作成してください",
    msgRenderStartFailed: "Render開始に失敗しました。",
    msgRenderStart: "Render開始",
    msgRenderStartRequestFailed: "Render開始リクエストに失敗しました",
    msgMetaSaveFailed: "メタ保存に失敗しました。",
    msgMetaSaved: "メタ保存",
    msgMetaSaveRequestFailed: "メタ保存リクエストに失敗しました",
    msgDeleteProjectFailed: "プロジェクトをゴミ箱へ移動できませんでした。",
    msgDeleteProjectDone: "プロジェクトをゴミ箱へ移動しました",
    msgDeleteRenderFailed: "動画をゴミ箱へ移動できませんでした。",
    msgDeleteRenderDone: "動画をゴミ箱へ移動しました",
    confirmDeleteProject: "このプロジェクトを削除しますか？\n\n対象:",
    confirmDeleteRender: "この動画を削除しますか？\n\n対象:",
  },
  en: {
    topEyebrow: "FORGE STUDIO",
    topTitle: "Forge Studio",
    topSubtitle: "Filter projects and move to the next task quickly.",
    quickReload: "Reload",
    rankReady: "Ready",
    rankWarming: "Warming up",
    rankSmooth: "On track",
    rankStable: "Stable",
    searchLabel: "Search",
    searchPlaceholder: "Filter by title / tags / app path",
    categoryLabel: "Category",
    statusLabel: "Status",
    sortLabel: "Sort",
    filterAll: "All categories",
    filterStatusAll: "All",
    filterStatusActiveDev: "Active dev",
    filterStatusReady: "Ready to watch",
    filterStatusNeedsRender: "Needs first render",
    filterStatusTemplate: "Templates / examples",
    sortRecent: "Most recent",
    sortTitle: "Title",
    sortCategory: "Category",
    showingPrefix: "Showing",
    showingSuffix: "projects",
    syncing: "dev status syncing...",
    guideTitle: "How to use",
    guideStepWatch: "Use Watch latest to review the newest render",
    guideStepManage: "Use Open control panel for Render / Dev / Meta",
    guideStepStart: "Start with Create render when there is no output yet",
    guideDismiss: "Dismiss",
    sectionFiltered: "Filtered projects",
    sectionFilteredBody: "Projects matching the current filters.",
    sectionActiveDev: "Running now",
    sectionActiveDevBody: "Projects currently in development.",
    sectionReady: "Ready to watch",
    sectionReadyBody: "Projects with recent renders.",
    sectionNeedsRender: "Needs first render",
    sectionNeedsRenderBody: "Projects without output yet.",
    sectionTemplate: "Templates & tools",
    sectionTemplateBody: "Templates and tooling projects.",
    noMatchTitle: "No matching projects",
    noMatchBody:
      "Relax the filters or add a new project with `pnpm create:project`.",
    primaryWatch: "Watch latest",
    primaryOpenDev: "Open dev",
    primaryRender: "Create render",
    primaryRunDev: "Run dev",
    actionManage: "Open control panel",
    actionRenderNow: "Run render",
    actionRefreshList: "Refresh list",
    actionDeleteRender: "Delete video",
    actionDeleteProject: "Delete project",
    actionRunDev: "Run dev",
    actionStopDev: "Stop dev",
    actionOpenDev: "Open dev",
    actionOpenInNewTab: "Open in new tab",
    actionClose: "Close",
    actionSave: "Save",
    stateActiveDev: "Active Dev",
    stateReady: "Ready",
    stateNeedsRender: "Needs Render",
    stateTemplate: "Template",
    labelLastRendered: "Last rendered",
    labelRenderFiles: "Render files",
    labelAppPath: "App path",
    labelLatest: "Latest",
    labelNoTags: "No tags",
    labelNeverRendered: "Never rendered",
    labelUnknown: "unknown",
    manageTitle: "Project control",
    manageSubtitle: "Heavy actions live here so cards can stay focused.",
    panelRenders: "Renders",
    panelDev: "Dev",
    panelMeta: "Meta",
    panelLatestRender: "Latest render",
    panelNoRender: "No rendered video yet.",
    panelRenderBody:
      "Refresh, preview, or remove render outputs only when needed.",
    panelDevBody: "Keep dev start, stop, and log inspection in one place.",
    panelMetaBody: "Edit project metadata and destructive actions here.",
    panelPreviewStatic: "Static preview",
    panelRunningOn: "Running on",
    panelStopped: "Stopped",
    panelLog: "Log",
    panelPid: "PID",
    panelTitle: "Title",
    panelDescription: "Description",
    panelTags: "Tags",
    panelCategory: "Category",
    panelThumbnail: "Thumbnail",
    placeholderTitle: "title",
    placeholderDescription: "description",
    placeholderTags: "tags (comma separated)",
    placeholderCategory: "category",
    placeholderThumbnail: "thumbnail path (e.g. public/thumbnail.svg)",
    previewTitle: "Quick Preview",
    previewApp: "App",
    previewUpdated: "Updated",
    previewSize: "Size",
    msgDevStartFailed: "Failed to start dev.",
    msgDevConnect: "Connected to dev",
    msgDevStarted: "Dev started",
    msgDevStartRequestFailed: "Dev start request failed",
    msgDevStopFailed: "Failed to stop dev.",
    msgAlreadyStopped: "Already stopped",
    msgDevStopped: "Dev stopped",
    msgDevStopRequestFailed: "Dev stop request failed",
    msgDevNotFound: "Dev server not found",
    msgRenderListFailed: "Failed to fetch render list",
    msgRenderListUpdated: "Render list updated",
    msgNoWatchable: "No watchable video yet",
    msgCreateRender: "Create a render first",
    msgRenderStartFailed: "Failed to start render.",
    msgRenderStart: "Render started",
    msgRenderStartRequestFailed: "Render start request failed",
    msgMetaSaveFailed: "Failed to save metadata.",
    msgMetaSaved: "Metadata saved",
    msgMetaSaveRequestFailed: "Metadata save request failed",
    msgDeleteProjectFailed: "Failed to move project to trash.",
    msgDeleteProjectDone: "Project moved to trash",
    msgDeleteRenderFailed: "Failed to move video to trash.",
    msgDeleteRenderDone: "Video moved to trash",
    confirmDeleteProject: "Delete this project?\n\nTarget:",
    confirmDeleteRender: "Delete this video?\n\nTarget:",
  },
} as const;

export function getCopy(language: Language) {
  return dashboardCopy[language];
}

export function getRankLabel(language: Language, rank: ForgeRank): string {
  const copy = getCopy(language);
  if (rank === "stable") return copy.rankStable;
  if (rank === "smooth") return copy.rankSmooth;
  if (rank === "warming") return copy.rankWarming;
  return copy.rankReady;
}

export function getStatusLabel(
  language: Language,
  status: StatusFilter,
): string {
  const copy = getCopy(language);
  if (status === "active_dev") return copy.filterStatusActiveDev;
  if (status === "ready_to_watch") return copy.filterStatusReady;
  if (status === "needs_render") return copy.filterStatusNeedsRender;
  if (status === "template") return copy.filterStatusTemplate;
  return copy.filterStatusAll;
}

export function getSortLabel(language: Language, sort: SortOption): string {
  const copy = getCopy(language);
  if (sort === "title") return copy.sortTitle;
  if (sort === "category") return copy.sortCategory;
  return copy.sortRecent;
}

export function getProjectStateLabel(
  language: Language,
  state: ProjectState,
): string {
  const copy = getCopy(language);
  if (state === "active_dev") return copy.stateActiveDev;
  if (state === "ready_to_watch") return copy.stateReady;
  if (state === "needs_render") return copy.stateNeedsRender;
  return copy.stateTemplate;
}
